Check for existance of GNU parallel

diff --git a/release b/release
--- a/release
+++ b/release
@@ -33,7 +33,15 @@ done
 [[ -z $(git status -s) ]] || { echo "Fail: Working directory is not clean"; exit 1; }
 
 # Check that for every author, we have at least name or mail recorded in Contributors.txt
-(git shortlog -se | parallel -C '\t|<' grep -Fq -e '{2}' -e '\<{3}' Contributors.txt) || { echo "Fail: contributor not listed"; exit 1; }
+# For each commit author, checks that either his/her name or respective mail
+# address appears in the contributors file. Note that a .mailcap file could be
+# introduced to canonicalize these names in the output of git-shortlog already.
+# Since this needs GNU parallel, the check is optional.
+if which parallel 2>/dev/null; then
+	{ (git shortlog -se | parallel -C '\t|<' grep -Fq -e '{2}' -e '\<{3}' Contributors.txt) || { echo "Fail: contributor not listed"; exit 1; }; }
+else
+	{ echo "Checking contributors needs GNU parallel, please make sure manually." 1>&2; }
+fi
 
 # Check there are no more [WIP] markers in Migrate and Readme
 [[ -z $(grep "WIP" Migration.md Readme.md) ]] || { echo "Fail: Work in progress in documentation"; exit 1; }
